name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::176040744685:role/rca-github-action-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd RCAx
             terraform init

      - name: Terraform Validate
        run: cd RCAx 
             terraform validate

      - name: Terraform Plan
        run: cd RCAx
             terraform plan -out=tfplan

      - name: Terraform Apply
        run: cd RCAx
             terraform apply -auto-approve tfplan
